const ADD_TO_CART = 'cart/ADD_TO_CART';
const REMOVE_FROM_CART = 'cart/REMOVE_FROM_CART';
const INCREMENT_AMOUNT = 'cart/INCREMENT_AMOUNT';
const DECREMENT_AMOUNT = 'cart/DECREMENT_AMOUNT';

export default {
  ADD_TO_CART,
  REMOVE_FROM_CART,
  INCREMENT_AMOUNT,
  DECREMENT_AMOUNT,
};
