const AUTH_REQUEST = 'auth/AUTH_REQUEST';
const AUTH_SUCCESS = 'auth/AUTH_SUCCESS';
const AUTH_ERROR = 'auth/AUTH_ERROR';
const SIGN_OUT_REQUEST = 'auth/SIGN_OUT_REQUEST';
const SIGN_OUT_SUCCESS = 'auth/SIGN_OUT_SUCCESS';
const SIGN_OUT_ERROR = 'auth/SIGN_OUT_ERROR';
const GET_CURRENT_USER_REQUEST = 'auth/GET_CURRENT_USER_REQUEST';
const GET_CURRENT_USER_SUCCESS = 'auth/GET_CURRENT_USER_SUCCESS';

export default {
  AUTH_REQUEST,
  AUTH_SUCCESS,
  AUTH_ERROR,
  SIGN_OUT_REQUEST,
  SIGN_OUT_SUCCESS,
  SIGN_OUT_ERROR,
  GET_CURRENT_USER_REQUEST,
  GET_CURRENT_USER_SUCCESS,
};
