const CATEGORIES_FETCH_REQUEST = 'menu/CATEGORIES_FETCH_REQUEST';
const CATEGORIES_FETCH_SUCCESS = 'menu/CATEGORIES_FETCH_SUCCESS';
const CATEGORIES_FETCH_ERROR = 'menu/CATEGORIES_FETCH_ERROR';

export default {
  CATEGORIES_FETCH_REQUEST,
  CATEGORIES_FETCH_SUCCESS,
  CATEGORIES_FETCH_ERROR,
};
