const MENU_FETCH_REQUEST = 'menu/FETCH_REQUEST';
const MENU_FETCH_SUCCESS = 'menu/FETCH_SUCCESS';
const MENU_FETCH_ERROR = 'menu/FETCH_ERROR';

export default {
  MENU_FETCH_REQUEST,
  MENU_FETCH_SUCCESS,
  MENU_FETCH_ERROR,
};
